### ISSUE TITLE
Mobile app usage

### ISSUE THREAD

**Issue by BrijenMakwana** [DiljotSG/MCU-Countdown#29]
I want to use this API for an app. But how will get next movie data in JSON just you get by clicking on the link?

**Comment by DiljotSG** [comment]
http://whenisthenextmcufilm.com/api

**Comment by BrijenMakwana** [comment]
> http://whenisthenextmcufilm.com/api

That's not what I'm talking about. I only get two movies data. How will I get all the upcoming MCU movies data present. But the API endpoint only gives two sets of movies. How will user know what date to provide

**Comment by DiljotSG** [comment]
Hi, that would need some changes to the code. I can add that to the list of changes I’d like to make. For now you can also pass in the date parameter and get the list of movies by looping through each “date after” value. Optionally you can use the TMDb API directly.
